misago/admin/urls.py
from django.conf.urls import url

from misago import admin

from .views import auth, index


urlpatterns = [
    # "misago:admin:index" link symbolises "root" of Misago admin links space
    # any request with path that falls below this one is assumed to be directed
    # at Misago Admin and will be checked by Misago Admin Middleware
    url(r'^$', index.admin_index, name='index'),
    url(r'^resolve-version/$', index.check_version, name='check-version'),
    url(r'^logout/$', auth.logout, name='logout'),
]

# Discover admin and register patterns
admin.discover_misago_admin()
urlpatterns += admin.urlpatterns()

misago/datamover/urls.py
from django.conf.urls import url

from . import views


urlpatterns = [
    url(r'^category/(?P<slug>(\w|-)+)-(?P<forum>\d+)/$', views.category_redirect),
    url(r'^forum/(?P<slug>(\w|-)+)-(?P<forum>\d+)/$', views.category_redirect),
    url(
        r'^forum/(?P<slug>(\w|-)+)-(?P<forum>\d+)/(?P<page>[1-9]([0-9]+)?)/$',
        views.category_redirect
    ),
    url(
        r'^forum/(?P<slug>(\w|-)+)-(?P<forum>\d+)/prefix/(?P<prefix>(\w|-)+)/$',
        views.category_redirect
    ),
    url(
        r'^forum/(?P<slug>(\w|-)+)-(?P<forum>\d+)/prefix/(?P<prefix>(\w|-)+)/(?P<page>[1-9]([0-9]+)?)/$',
        views.category_redirect
    ),
    url(r'^forum/(?P<slug>(\w|-)+)-(?P<forum>\d+)/start/$', views.category_redirect),
]

urlpatterns += [
    url(r'^thread/(?P<slug>(\w|-)+)-(?P<thread>\d+)/edit/$', views.thread_redirect),
    url(r'^thread/(?P<slug>(\w|-)+)-(?P<thread>\d+)/reply/$', views.thread_redirect),
    url(r'^thread/(?P<slug>(\w|-)+)-(?P<thread>\d+)/vote/$', views.thread_redirect),
    url(r'^thread/(?P<slug>(\w|-)+)-(?P<thread>\d+)/poll/$', views.thread_redirect),
    url(r'^thread/(?P<slug>(\w|-)+)-(?P<thread>\d+)/(?P<post>\d+)/reply/$', views.thread_redirect),
    url(r'^thread/(?P<slug>(\w|-)+)-(?P<thread>\d+)/(?P<post>\d+)/edit/$', views.thread_redirect),
    url(r'^thread/(?P<slug>(\w|-)+)-(?P<thread>\d+)/$', views.thread_redirect),
    url(
        r'^thread/(?P<slug>(\w|-)+)-(?P<thread>\d+)/(?P<page>[1-9]([0-9]+)?)/$',
        views.thread_redirect
    ),
    url(r'^thread/(?P<slug>(\w|-)+)-(?P<thread>\d+)/last/$', views.thread_redirect),
    url(r'^thread/(?P<slug>(\w|-)+)-(?P<thread>\d+)/find-(?P<post>\d+)/$', views.thread_redirect),
    url(r'^thread/(?P<slug>(\w|-)+)-(?P<thread>\d+)/new/$', views.thread_redirect),
    url(r'^thread/(?P<slug>(\w|-)+)-(?P<thread>\d+)/moderated/$', views.thread_redirect),
    url(r'^thread/(?P<slug>(\w|-)+)-(?P<thread>\d+)/reported/$', views.thread_redirect),
    url(r'^thread/(?P<slug>(\w|-)+)-(?P<thread>\d+)/show-hidden/$', views.thread_redirect),
    url(r'^thread/(?P<slug>(\w|-)+)-(?P<thread>\d+)/watch/$', views.thread_redirect),
    url(r'^thread/(?P<slug>(\w|-)+)-(?P<thread>\d+)/watch/email/$', views.thread_redirect),
    url(r'^thread/(?P<slug>(\w|-)+)-(?P<thread>\d+)/unwatch/$', views.thread_redirect),
    url(r'^thread/(?P<slug>(\w|-)+)-(?P<thread>\d+)/unwatch/email/$', views.thread_redirect),
    url(
        r'^thread/(?P<slug>(\w|-)+)-(?P<thread>\d+)/(?P<post>\d+)/upvote/$', views.thread_redirect
    ),
    url(
        r'^thread/(?P<slug>(\w|-)+)-(?P<thread>\d+)/(?P<post>\d+)/downvote/$',
        views.thread_redirect
    ),
    url(
        r'^thread/(?P<slug>(\w|-)+)-(?P<thread>\d+)/(?P<post>\d+)/report/$', views.thread_redirect
    ),
    url(
        r'^thread/(?P<slug>(\w|-)+)-(?P<thread>\d+)/(?P<post>\d+)/show-report/$',
        views.thread_redirect
    ),
    url(r'^thread/(?P<slug>(\w|-)+)-(?P<thread>\d+)/delete/$', views.thread_redirect),
    url(r'^thread/(?P<slug>(\w|-)+)-(?P<thread>\d+)/hide/$', views.thread_redirect),
    url(r'^thread/(?P<slug>(\w|-)+)-(?P<thread>\d+)/show/$', views.thread_redirect),
    url(
        r'^thread/(?P<slug>(\w|-)+)-(?P<thread>\d+)/(?P<post>\d+)/delete/$', views.thread_redirect
    ),
    url(r'^thread/(?P<slug>(\w|-)+)-(?P<thread>\d+)/(?P<post>\d+)/hide/$', views.thread_redirect),
    url(r'^thread/(?P<slug>(\w|-)+)-(?P<thread>\d+)/(?P<post>\d+)/show/$', views.thread_redirect),
    url(
        r'^thread/(?P<slug>(\w|-)+)-(?P<thread>\d+)/checkpoint/(?P<checkpoint>\d+)/delete/$',
        views.thread_redirect
    ),
    url(
        r'^thread/(?P<slug>(\w|-)+)-(?P<thread>\d+)/checkpoint/(?P<checkpoint>\d+)/hide/$',
        views.thread_redirect
    ),
    url(
        r'^thread/(?P<slug>(\w|-)+)-(?P<thread>\d+)/checkpoint/(?P<checkpoint>\d+)/show/$',
        views.thread_redirect
    ),
    url(r'^thread/(?P<slug>(\w|-)+)-(?P<thread>\d+)/(?P<post>\d+)/info/$', views.thread_redirect),
    url(r'^thread/(?P<slug>(\w|-)+)-(?P<thread>\d+)/(?P<post>\d+)/votes/$', views.thread_redirect),
    url(
        r'^thread/(?P<slug>(\w|-)+)-(?P<thread>\d+)/(?P<post>\d+)/changelog/$',
        views.thread_redirect
    ),
    url(
        r'^thread/(?P<slug>(\w|-)+)-(?P<thread>\d+)/(?P<post>\d+)/changelog/(?P<change>\d+)/$',
        views.thread_redirect
    ),
    url(
        r'^thread/(?P<slug>(\w|-)+)-(?P<thread>\d+)/(?P<post>\d+)/changelog/(?P<change>\d+)/revert/$',
        views.thread_redirect
    ),
]

urlpatterns += [
    url(
        r'^private-threads/(?P<slug>(\w|-)+)-(?P<thread>\d+)/edit/$', views.private_thread_redirect
    ),
    url(
        r'^private-threads/(?P<slug>(\w|-)+)-(?P<thread>\d+)/reply/$',
        views.private_thread_redirect
    ),
    url(
        r'^private-threads/(?P<slug>(\w|-)+)-(?P<thread>\d+)/vote/$', views.private_thread_redirect
    ),
    url(
        r'^private-threads/(?P<slug>(\w|-)+)-(?P<thread>\d+)/poll/$', views.private_thread_redirect
    ),
    url(
        r'^private-threads/(?P<slug>(\w|-)+)-(?P<thread>\d+)/(?P<post>\d+)/reply/$',
        views.private_thread_redirect
    ),
    url(
        r'^private-threads/(?P<slug>(\w|-)+)-(?P<thread>\d+)/(?P<post>\d+)/edit/$',
        views.private_thread_redirect
    ),
    url(r'^private-threads/(?P<slug>(\w|-)+)-(?P<thread>\d+)/$', views.private_thread_redirect),
    url(
        r'^private-threads/(?P<slug>(\w|-)+)-(?P<thread>\d+)/(?P<page>[1-9]([0-9]+)?)/$',
        views.private_thread_redirect
    ),
    url(
        r'^private-threads/(?P<slug>(\w|-)+)-(?P<thread>\d+)/last/$', views.private_thread_redirect
    ),
    url(
        r'^private-threads/(?P<slug>(\w|-)+)-(?P<thread>\d+)/find-(?P<post>\d+)/$',
        views.private_thread_redirect
    ),
    url(
        r'^private-threads/(?P<slug>(\w|-)+)-(?P<thread>\d+)/new/$', views.private_thread_redirect
    ),
    url(
        r'^private-threads/(?P<slug>(\w|-)+)-(?P<thread>\d+)/moderated/$',
        views.private_thread_redirect
    ),
    url(
        r'^private-threads/(?P<slug>(\w|-)+)-(?P<thread>\d+)/reported/$',
        views.private_thread_redirect
    ),
    url(
        r'^private-threads/(?P<slug>(\w|-)+)-(?P<thread>\d+)/show-hidden/$',
        views.private_thread_redirect
    ),
    url(
        r'^private-threads/(?P<slug>(\w|-)+)-(?P<thread>\d+)/watch/$',
        views.private_thread_redirect
    ),
    url(
        r'^private-threads/(?P<slug>(\w|-)+)-(?P<thread>\d+)/watch/email/$',
        views.private_thread_redirect
    ),
    url(
        r'^private-threads/(?P<slug>(\w|-)+)-(?P<thread>\d+)/unwatch/$',
        views.private_thread_redirect
    ),
    url(
        r'^private-threads/(?P<slug>(\w|-)+)-(?P<thread>\d+)/unwatch/email/$',
        views.private_thread_redirect
    ),
    url(
        r'^private-threads/(?P<slug>(\w|-)+)-(?P<thread>\d+)/(?P<post>\d+)/upvote/$',
        views.private_thread_redirect
    ),
    url(
        r'^private-threads/(?P<slug>(\w|-)+)-(?P<thread>\d+)/(?P<post>\d+)/downvote/$',
        views.private_thread_redirect
    ),
    url(
        r'^private-threads/(?P<slug>(\w|-)+)-(?P<thread>\d+)/(?P<post>\d+)/report/$',
        views.private_thread_redirect
    ),
    url(
        r'^private-threads/(?P<slug>(\w|-)+)-(?P<thread>\d+)/(?P<post>\d+)/show-report/$',
        views.private_thread_redirect
    ),
    url(
        r'^private-threads/(?P<slug>(\w|-)+)-(?P<thread>\d+)/delete/$',
        views.private_thread_redirect
    ),
    url(
        r'^private-threads/(?P<slug>(\w|-)+)-(?P<thread>\d+)/hide/$', views.private_thread_redirect
    ),
    url(
        r'^private-threads/(?P<slug>(\w|-)+)-(?P<thread>\d+)/show/$', views.private_thread_redirect
    ),
    url(
        r'^private-threads/(?P<slug>(\w|-)+)-(?P<thread>\d+)/(?P<post>\d+)/delete/$',
        views.private_thread_redirect
    ),
    url(
        r'^private-threads/(?P<slug>(\w|-)+)-(?P<thread>\d+)/(?P<post>\d+)/hide/$',
        views.private_thread_redirect
    ),
    url(
        r'^private-threads/(?P<slug>(\w|-)+)-(?P<thread>\d+)/(?P<post>\d+)/show/$',
        views.private_thread_redirect
    ),
    url(
        r'^private-threads/(?P<slug>(\w|-)+)-(?P<thread>\d+)/checkpoint/(?P<checkpoint>\d+)/delete/$',
        views.private_thread_redirect
    ),
    url(
        r'^private-threads/(?P<slug>(\w|-)+)-(?P<thread>\d+)/checkpoint/(?P<checkpoint>\d+)/hide/$',
        views.private_thread_redirect
    ),
    url(
        r'^private-threads/(?P<slug>(\w|-)+)-(?P<thread>\d+)/checkpoint/(?P<checkpoint>\d+)/show/$',
        views.private_thread_redirect
    ),
    url(
        r'^private-threads/(?P<slug>(\w|-)+)-(?P<thread>\d+)/(?P<post>\d+)/info/$',
        views.private_thread_redirect
    ),
    url(
        r'^private-threads/(?P<slug>(\w|-)+)-(?P<thread>\d+)/(?P<post>\d+)/votes/$',
        views.private_thread_redirect
    ),
    url(
        r'^private-threads/(?P<slug>(\w|-)+)-(?P<thread>\d+)/(?P<post>\d+)/changelog/$',
        views.private_thread_redirect
    ),
    url(
        r'^private-threads/(?P<slug>(\w|-)+)-(?P<thread>\d+)/(?P<post>\d+)/changelog/(?P<change>\d+)/$',
        views.private_thread_redirect
    ),
    url(
        r'^private-threads/(?P<slug>(\w|-)+)-(?P<thread>\d+)/(?P<post>\d+)/changelog/(?P<change>\d+)/revert/$',
        views.private_thread_redirect
    ),
]

urlpatterns += [
    url(r'^users/(?P<username>\w+)-(?P<user>\d+)/', views.user_redirect),
    url(r'^users/(?P<username>\w+)-(?P<user>\d+)/(?P<page>\d+)/', views.user_redirect),
    url(r'^users/(?P<username>\w+)-(?P<user>\d+)/(?P<subpage>(\w|-)+)/', views.user_redirect),
    url(
        r'^users/(?P<username>\w+)-(?P<user>\d+)/(?P<subpage>(\w|-)+)/(?P<page>\d+)/',
        views.user_redirect
    ),
]

misago/project_template/project_name/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin
from django.views.generic import TemplateView

from misago.core.views import javascript_catalog
from misago.users.forms.auth import AdminAuthenticationForm


admin.autodiscover()
admin.site.login_form = AdminAuthenticationForm


urlpatterns = [
    url(r'^', include('misago.urls', namespace='misago')),

    # Javascript translations
    url(r'^django-i18n.js$', javascript_catalog, name='django-i18n'),

    # Uncomment next line if you plan to use Django admin for 3rd party apps
    #url(r'^django-admin/', include(admin.site.urls)),
]


# If debug mode is enabled, include debug toolbar
if settings.DEBUG:
    import debug_toolbar
    urlpatterns += [
        url(r'^__debug__/', include(debug_toolbar.urls)),
    ]


# Use static file server for static and media files (debug only)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


# Error Handlers
# Misago needs those handlers to deal with errors raised by it's middlewares
# If you replace those handlers with custom ones, make sure you decorate them
# with shared_403_exception_handler or shared_404_exception_handler
# decorators that are defined in misago.views.errorpages module!
handler403 = 'misago.core.errorpages.permission_denied'
handler404 = 'misago.core.errorpages.page_not_found'

misago/urls.py
from django.conf.urls import include, url
from django.views.generic import TemplateView

from misago.conf import settings
from misago.core.views import forum_index


# Register Misago Apps
urlpatterns = [
    url(r'^', include('misago.legal.urls')),
    url(r'^', include('misago.users.urls')),
    url(r'^', include('misago.categories.urls')),
    url(r'^', include('misago.threads.urls')),
    url(r'^', include('misago.search.urls')),

    # default robots.txt
    url(
        r'^robots.txt$',
        TemplateView.as_view(content_type='text/plain', template_name='misago/robots.txt')
    ),

    # "misago:index" link symbolises "root" of Misago links space
    # any request with path that falls below this one is assumed to be directed
    # at Misago and will be handled by misago.views.exceptionhandler if it
    # results in Http404 or PermissionDenied exception
    url(r'^$', forum_index, name='index'),
]

# Register API
apipatterns = [
    url(r'^', include('misago.categories.urls.api')),
    url(r'^', include('misago.markup.urls')),
    url(r'^', include('misago.threads.urls.api')),
    url(r'^', include('misago.users.urls.api')),
    url(r'^', include('misago.search.urls.api')),
]

urlpatterns += [
    url(r'^api/', include(apipatterns, namespace='api')),
]

# Register Misago ACP
if settings.MISAGO_ADMIN_PATH:
    # Admin patterns recognised by Misago
    adminpatterns = [
        url(r'^', include('misago.admin.urls')),
    ]

    admin_prefix = r'^%s/' % settings.MISAGO_ADMIN_PATH
    urlpatterns += [
        url(admin_prefix, include(adminpatterns, namespace='admin')),
    ]

# Make error pages accessible casually in DEBUG
if settings.DEBUG:
    from misago.core import errorpages
    urlpatterns += [
        url(r'^403/$', errorpages.permission_denied),
        url(r'^404/$', errorpages.page_not_found),
        url(r'^405/$', errorpages.not_allowed),
        url(r'^csrf-failure/$', errorpages.csrf_failure),
    ]

misago/templates/misago/admin/base.html
{% extends "misago/admin/base_thin.html" %}
{% load staticfiles %}


{% block body %}
{% include "misago/admin/navbar.html" %}
{% include "misago/admin/messages.html" %}

{% block content %}{% endblock %}

<footer class="admin-footer">
  <div class="misago-branding text-center">
    <a href="http://misago-project.org">
      <span class="subscript">powered by</span>
      <img src="{% static 'misago/admin/img/misago.png' %}" height="22px" alt="Misago">
    </a>
  </div>
</footer>

{% include "misago/admin/logout.html" %}

{# We include JavaScript at the end of page body so it renders faster #}
<script type="text/javascript" src="{% static 'misago/admin/js/jquery.js' %}"></script>
<script type="text/javascript" src="{% static 'misago/admin/js/bootstrap.js' %}"></script>
<script type="text/javascript" src="{% static 'misago/admin/js/moment.min.js' %}"></script>
<script type="text/javascript" src="{% static 'misago/admin/js/bootstrap-datetimepicker.min.js' %}"></script>
<script type="text/javascript" src="{% static 'misago/admin/js/misago-datetimepicker.js' %}"></script>
<script type="text/javascript" src="{% static 'misago/admin/js/misago-timestamps.js' %}"></script>
<script type="text/javascript" src="{% static 'misago/admin/js/misago-tooltips.js' %}"></script>
<script type="text/javascript" src="{% static 'misago/admin/js/misago-tables.js' %}"></script>
<script type="text/javascript" src="{% static 'misago/admin/js/misago-yesnoswitch.js' %}"></script>
{% block javascripts %}{% endblock javascripts %}
{% endblock body %}

misago/templates/misago/admin/base_thin.html
{% load i18n staticfiles %}
<!DOCTYPE html>
<html lang="{{ LANGUAGE_CODE }}">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %}{% trans "Misago Administration" %}{% endblock %}</title>
    <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
      <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
    <link href="{% static 'misago/admin/css/style.css' %}" rel="stylesheet">
    <link rel="apple-touch-icon" href="{% static 'apple-touch-icon.png' %}">
    <link rel="apple-touch-icon" sizes="57x57" href="{% static 'apple-touch-icon-57.png' %}">
    <link rel="apple-touch-icon" sizes="72x72" href="{% static 'apple-touch-icon-72.png' %}">
    <link rel="apple-touch-icon" sizes="76x76" href="{% static 'apple-touch-icon-76.png' %}">
    <link rel="apple-touch-icon" sizes="80x80" href="{% static 'apple-touch-icon-80.png' %}">
    <link rel="apple-touch-icon" sizes="114x114" href="{% static 'apple-touch-icon-114.png' %}">
    <link rel="apple-touch-icon" sizes="120x120" href="{% static 'apple-touch-icon-120.png' %}">
    <link rel="apple-touch-icon" sizes="144x144" href="{% static 'apple-touch-icon-144.png' %}">
    <link rel="apple-touch-icon" sizes="152x152" href="{% static 'apple-touch-icon-152.png' %}">
    <link rel="apple-touch-icon" sizes="167x167" href="{% static 'apple-touch-icon-167.png' %}">
    <link rel="apple-touch-icon" sizes="180x180" href="{% static 'apple-touch-icon-180.png' %}">
    <link rel="shortcut icon" href="{% static 'favicon.ico' %}">
    <link rel="icon" sizes="16x16 32x32" href="{% static 'favicon.ico' %}">
  </head>
  <body>

    {% block body %}{% endblock %}

  </body>
</html>

misago/templates/misago/admin/index.html
{% extends "misago/admin/base.html" %}
{% load i18n %}


{% block title %}{% trans "Home" %} | {{ block.super }}{% endblock %}


{% block content %}
<div class="page-header">
  <div class="container">
    <h1>
      <span class="fa fa-home"></span>
      {% trans "Administration Home" %}
    </h1>
  </div>
</div>

<div class="container">
  <div class="row">
    <div class="col-md-8">



    </div>
    <div class="col-md-4">

      <table class="table version-check">
        <thead>
          <tr>
            <th colspan="2">
              <h4>
                <span class="fa fa-github"></span>
                {% trans "Misago version" %}
              </h4>
            </th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <td class="text-center">
              {% if version_check %}
              <p class="lead text-{% if version_check.is_error %}error{% else %}success{% endif %}">
                {% if version_check.is_error %}
                <span class="fa fa-times fa-lg fa-fw"></span>
                {% else %}
                <span class="fa fa-check fa-lg fa-fw"></span>
                {% endif %}
                {{ version_check.message }}
              </p>
              {% else %}
              <form method="POST">
                {% csrf_token %}
                <button type="submit" class="btn btn-default">
                  <span class="fa fa-question-circle fa-fw"></span>
                  <span class="name">{% trans "Check version" %}</span>
                </button>
              </form>
              {% endif %}
            </td>
          </tr>
        </tbody>
      </table>

      <table class="table">
        <thead>
          <tr>
            <th colspan="2">
              <h4>
                <span class="fa fa-database"></span>
                {% trans "DB Contents" %}
              </h4>
            </th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <td>{% trans "Threads" %}</td>
            <td>{{ db_stats.threads }}</td>
          </tr>
          <tr>
            <td>{% trans "Posts" %}</td>
            <td>{{ db_stats.posts }}</td>
          </tr>
          <tr>
            <td>{% trans "Users" %}</td>
            <td>{{ db_stats.users }}</td>
          </tr>
          {% if db_stats.inactive_users %}
          <tr>
            <td>{% trans "Inactive users" %}</td>
            <td>
              <a href="{% url "misago:admin:users:accounts:index" %}?inactive=1">{{ db_stats.inactive_users }}</a>
            </td>
          </tr>
          {% endif %}
        </tbody>
      </table>

    </div>
  </div>
</div>
{% endblock content %}


{% block javascripts %}
<script type="text/javascript">
  $(function () {
    var $version_check = $('.version-check');
    var $outcome = $version_check.find('td');

    $version_check.find('form').submit(function() {
      var $form = $(this);
      var $button = $(this).find("button");
      $button.attr("disabled", "disabled");
      $button.find('.fa').attr("class", "fa fa-refresh fa-fw fa-spin");
      $button.find('.name').text("{% trans "Checking..." %}");

      $.post("{% url 'misago:admin:check-version' %}", $form.serialize(), function(data) {
        if (data.is_error) {
          var $message = $('<p class="lead text-danger"><span class="fa fa-times fa-lg fa-fw"></span></p>');
        } else {
          var $message = $('<p class="lead text-success"><span class="fa fa-check fa-lg fa-fw"></span></p>');
        }
        $message.append(" " + data.message);
        $form.fadeOut();
        $outcome.html($message);
      });

      return false;
    });
  });
</script>
{% endblock javascripts %}

misago/templates/misago/admin/login.html
{% extends "misago/admin/base_thin.html" %}
{% load i18n staticfiles %}


{% block title %}{% trans "Log in" %} | {% if target == "django" %}{% trans "Django Admin" %}{% else %}{% trans "Misago Admin" %}{% endif %}{% endblock %}


{% block body %}
<div class="login-form">

  {% if target == "misago" %}
  <div class="form-admin-logo">
    <img src="{% static 'misago/admin/img/misago.png' %}" alt="Misago">
  </div>
  {% elif target == "django" %}
  <div class="form-admin-logo">
    <img src="{% static 'misago/admin/img/django.png' %}" alt="Django">
  </div>
  {% endif  %}

  <div class="form-panel">
    <form method="POST" role="form">
      {% csrf_token %}

      <div class="form-header">
        <h1>{% trans "Administration" %}</h1>
      </div>

      <div class="form-body no-fieldsets">

        {% for error in form.non_field_errors %}
        <div class="misago-alerts">
          <p class="alert alert-danger lead">
            {{ error }}
            <br>{% trans "Please try again." %}
          </p>
        </div>
        {% endfor %}
        {% for message in messages %}
        <div class="misago-alerts">
          {% if 'success' in message.tags %}
          <p class="alert alert-success lead">
          {% elif 'warning' in message.tags %}
          <p class="alert alert-warning lead">
          {% elif 'error' in message.tags %}
          <p class="alert alert-danger lead">
          {% else %}
          <p class="alert alert-info lead">
          {% endif %}
            {{ message }}
          </p>
        </div>
        {% endfor %}

        <div class="form-group">
          <div class="control-input">
            <input type="text" name="username" class="form-control input-lg" placeholder="{% trans "Username or e-mail" %}" {% if form.username.value %}value="{{ form.username.value }}"{% endif %}>
          </div>
        </div>
        <div class="form-group">
          <div class="control-input">
            <input type="password" name="password" class="form-control input-lg" placeholder="{% trans "Password" %}">
          </div>
        </div>
        <div class="form-group">
          <div class="control-input">
            <button class="btn btn-primary btn-block btn-lg">{% trans "Sign in" %}</button>
          </div>
        </div>

      </div>


    </form>
  </div>

</div>
{% endblock body %}

misago/templates/misago/admin/logout.html
{% load i18n %}
<!-- Log out modal -->
<div class="modal fade" id="logout-modal" tabindex="-1" role="dialog" aria-labelledby="logoutModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h4 class="modal-title" id="logoutModalLabel">{% trans "Log out?" %}</h4>
      </div>
      <div class="modal-body">

        <div class="row">
          <div class="col-md-6">

            <form action="{% url 'misago:admin:logout' %}" method="post">
              {% csrf_token %}
              <button type="submit" class="btn btn-primary btn-block">
                <span class="fa fa-lock"></span>
                {% trans "Log out from admin" %}
              </button>
            </form>

          </div>
          <div class="col-md-6">

            <form action="{% url 'misago:logout' %}" method="post">
              {% csrf_token %}
              <button type="submit" class="btn btn-danger btn-block">
                <span class="fa fa-power-off"></span>
                {% trans "Log out completely" %}
              </button>
            </form>

          </div>
        </div>

      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default btn-lg btn-block" data-dismiss="modal">{% trans "Cancel" %}</button>
      </div>
    </div>
  </div>
</div>